<div id="page_banner">			
    <?php foreach($this->listaBanner as $index):?>
    <a href="<?php echo $index['UrlBanner']; ?>">
        <img src="<?php echo CST_Server_ServerDinamic::getUrl(); ?>/img/banner/<?php echo $index['ImagenBanner']; ?>" alt="" border="0" />
    </a>
    <?php endforeach;?>
</div>
<div id="ticker">
    <p style="visibility:visible;opacity:1;">
        <a href="#">
            <span style="color:#006B6E; font-weight:bold;">&iquest;Desea saber m&aacute;s acerca de ESET Endpoint Solutions? <strong>Haga clic aqu&iacute;</strong>
            </span>
        </a>
    </p>
</div>

<div id="content_wrapper">
    <div id="content_homepage" style="padding-top:10px; padding-bottom:15px;">
        <div id="home_slides_window">
            <div id="home_slides">
                <?php foreach($this->listaAreas as $index): ?>
                <div class="home_slide">
                    <h2><?php echo $index['NombreArea']; ?></h2>
                    <a href="/servicio/<?php echo $index['SlugArea']; ?>" onclick="_hbLink('Slide Image ESS');">
                        <img src="<?php echo CST_Server_ServerDinamic::getUrl(); ?>/img/area/<?php echo $index['ImagenArea']?>" alt="ESET Smart Security. Antivirus, Antispyware, Firewall y Antispam en un único producto." /></a>
                    <div class="home_slide_desc">
<!--                        <strong>ESET Smart Security 5 </strong> incorpora un firewall y antispam al reconocido ESET NOD32 Antivirus protegiendo su equipo e informaci&oacute;n de los ataques de Internet y de los molestos correos basura, adem&aacute;s ahora puede proteger a sus hijos del contenido inapropiado circulando en la web utilizando el control parental -->
                        <?php echo $index['DescripcionCortaArea']; ?>
                        <br/>
                        <a href="/servicio/<?php echo $index['SlugArea']; ?>" onclick="_hbLink('Learn More ESS');">Conozca más</a> <img src="<?php echo CST_Server_ServerStatic::getUrl(); ?>/images/double_arrow_right.gif" alt="Conozca más" />
                    </div>
<!--                    <p><a href="/comprar/" onclick="_hbLink('Buy ESS Button');"><img src="<?php echo CST_Server_ServerStatic::getUrl(); ?>/images/boton-comprar-eset.png" alt="Adquiera ESET Smart Security y ESET NOD32 Antivirus." style="margin-right:10px" /></a>
                        <a href="/download/trial-gratuito/smart-security" onclick="_hbLink('Trial ESS Button');"><img src="<?php echo CST_Server_ServerStatic::getUrl(); ?>/images/boton-trial-gratuito-eset.gif" alt="Descargue gratis ESET Smart Security y ESET NOD32 Antivirus por 30 días." /></a></p>-->
                </div>
                <?php endforeach; ?>
                <div class="home_slide">
                    <h2>Accesos R&aacute;pidos</h2>
                    <div class="narrow_column_content" style="padding:0px;">
                        <div class="sidebox-outer-180">
                            <div class="sidebox-180">
                                <div class="sidebox-list"> 
                                    <a href="/comprar/" style="padding:5px 0 5px 15px;"><img src="/images/icons/icono_acceso_comprar.png" width="16" height="16" align="absmiddle" /> Comprar</a> 
                                    <a href="/registracion-producto/" style="padding:5px 0 5px 15px;"><img src="/images/icons/icono_acceso_activacion.png" width="16" height="16" align="absmiddle" /> Activaci&oacute;n</a>
                                    <a href="/download/trial-gratuito/" style="padding:5px 0 5px 15px;"><img src="/images/icons/icono_acceso_triall_gratuito.png" width="16" height="16" align="absmiddle" /> Trial Gratuito</a> 
                                    <a href="/online-scanner/" style="padding:5px 0 5px 15px;"><img src="/images/icons/icono_acceso_online_scanner.png" width="16" height="16" align="absmiddle" /> Online Scanner</a> 
                                    <a href="/hogar/compare-eset/" style="padding:5px 0 5px 15px;"><img src="/images/icons/icono_acceso_eset_vs_competencia.png" width="16" height="16" align="absmiddle" /> ESET vs. la competencia</a> 
                                    <!--a href="/pe/press-center/events/" style="padding:5px 0 5px 15px;"><img src="/images/icons/icono_acceso_eventos.png" width="16" height="16" align="absmiddle" /> Eventos</a--> 
                                    <a href="http://blogs.eset-la.com/" style="padding:5px 0 5px 15px;"><img src="/images/icons/icono_acceso_blog.png" width="16" height="16" align="absmiddle" /> Blogs de ESET</a> 
                                    <a href="/compania/newsletter/" style="padding:5px 0 5px 15px;"><img src="/images/icons/icono_acceso_boletin.png" width="16" height="16" align="absmiddle" /> Bolet&iacute;n</a> 
                                    <a href="/renew/" style="padding:5px 0 5px 15px;"><img src="/images/icons/icono_acceso_comprar.png" width="16" height="16" align="absmiddle" /> Renovar en l&iacute;nea</a> 
                                    <a href="/comprar/obtener-presupuesto-gratuito" style="padding:5px 0 5px 15px;"><img src="/images/icons/icono_acceso_presupuesto_gratuito.png" width="16" height="16" align="absmiddle" /> Presupuesto Gratuito</a> 
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="quicklinks_cell">
    <div id="quicklinks">
        <a href="/comprar" title="">Comprar</a> | <a href="http://blogs.eset-la.com/" target="_blank" title="">Blogs de ESET</a> | <a href="/registracion-producto" title="">Activar Software</a> | <a href="/download/trial-gratuito" title="">Evaluación Gratuita</a> | <a href="/online-scanner" title="">Online Scanner</a> | <a href="/hogar/compare-eset" title="">ESET vs. Competencia</a> | <a href="/pe/centro-prensa" title="">Centro de Prensa</a> | <a href="/centro-amenazas" title="">Centro de Amenazas</a> | <a href="/soporte/contacto" title="">Soporte</a>
    </div>
    <div id="product_selector">
        <div style="float:left; margin-right:6px"><strong>Todos nuestros Productos:</strong></div>
        <select id="quicklink_products">
            <option selected="selected">Seleccionar un Producto</option>
            <option>ESET Smart Security</option>
            <option>ESET NOD32 Antivirus</option>
            <option>ESET Cybersecurity para Mac</option>
            <option>ESET Mobile Security</option>
            <option>ESET Endpoint Security</option>
            <option>ESET Endpoint Antivirus</option>
            <option>ESET Remote Administrator</option>
            <option>ESET Server Security</option>
            <option>ESET Online Scanner</option>
            <option>ESET SysInspector</option>
        </select>
    </div>
</div>
<script type="text/javascript">
    var quicklink_products = {"ESET Smart Security":"\/hogar\/smart-security","ESET NOD32 Antivirus":"\/hogar\/nod32-antivirus","ESET Cybersecurity para Mac":"\/hogar\/cybersecurity-mac","ESET Mobile Security":"\/hogar\/mobile-security-antivirus","ESET Endpoint Security":"\/empresas\/medianas\/eset-endpoint-security","ESET Endpoint Antivirus":"\/empresas\/medianas\/eset-endpoint-antivirus","ESET Remote Administrator":"\/empresas\/remote-administrator","ESET Server Security":"\/empresas\/server-security","ESET Online Scanner":"\/online-scanner","ESET SysInspector":"\/download\/sysinspector"};
    document.getElementById('quicklink_products').onchange = function() {
        if(this.selectedIndex > 0) {
            window.location = quicklink_products[this.options[this.selectedIndex].innerHTML];
        }
    }
</script>    
