<div class="navbar2" id="treeMenu">
    <ul>
        <?php
        $string = '';
        foreach ($this->listaCategoriasNavigator as $index) {
            if ($this->getPathInfo == $index['uri']) {
                $string.= '<li class="active">';
            } else {
                $string.= '<li>';
            }
            $string.= '<a class="parent" href="' . $index['uri'] . '" >' . $index['label'] . '</a><span></span>';
            if (isset($index['pages']) && !empty($index['pages'])) {
                $string.= '<div><ul>';
                foreach ($index['pages'] as $index2) {
                    if ($this->getPathInfo == $index2['uri']) {
                        $string.= '<li class="active">';
                    } else {
                        $string.= '<li>';
                    }
                    $string.= '<span></span><a class="parent" href="' . $index2['uri'] . '" >' . $index2['label'] . '</a><div>';
                    if (isset($index2['pages']) && !empty($index2['pages'])) {
                        $string.= '<ul>';
                        foreach ($index2['pages'] as $index3) {
                            if ($this->getPathInfo == $index3['uri']) {
                                $string.= '<li class="active">';
                            } else {
                                $string.= '<li>';
                            }
                            $string.= '<span></span><a href="' . $index3['uri'] . '" >' . $index3['label'] . '</a>';
                            $string.= '</li>';
                        }
                        $string.= '</ul>';
                    }
                    $string.= '</div></li>';
                }
                $string.= '</ul></div>';
            }
            $string.= '</li>';
        }
        echo $string;
        ?>
    </ul>
</div>
<?php if(!empty($this->listaMarcas)){
    
    ?>
<div class="productos_marcas_treeMenu">
    <div>Marcas</div>
    <ul>
    <?php foreach($this->listaMarcas as $index):?>
        <li>
            
            <?php 
            $href='?marca='.$index['SlugMarca'];
            $checked='';
            $arrayfiltro = explode(',',$this->slugMarcaFiltro);
            
            
            
            if(in_array($index['SlugMarca'], $arrayfiltro)){
                $newArrayFiltro = $arrayfiltro;
                unset($newArrayFiltro[array_search($index['SlugMarca'],$newArrayFiltro)]);
                $newSlugMarcaFiltro = implode(',',$newArrayFiltro);
                $href='?marca='.$newSlugMarcaFiltro;
                $checked = ' checked="checked" ';
            }else{
                if($this->slugMarcaFiltro!='')
                $href='?marca='.$index['SlugMarca'].','.$this->slugMarcaFiltro;
            }
            ?>
            <a href="<?php echo $href ?>">
                <input type="checkbox" 
                       <?php echo $checked; ?>
                       name="marcas[]" 
                       value="<?php echo $index['SlugMarca'] ?>"/>  
                       <?php echo $index['NombreMarca'] ?> 
            </a>
        </li>
    <?php endforeach;?>
        <li> 
            <a href="/productos"> <input type="checkbox" name="marcas[]" value=""/> Todas </a>
        </li>
    </ul>
</div>
<?php } ?>