<div>
    [<a href="/admin/marca/create-marca">Nueva Marca</a>]
</div>
<hr></hr>
<table>
    <tr>
        <td>IdMarca<hr></hr></td>
        <td>Nombre<hr></hr></td>        
        <td>Imagen<hr></hr></td>
        <td colspan="2" >Acciones<hr></hr></td>
    </tr>
<?php foreach($this->marca as $index)
{
?>
    <tr>
        <td><?php echo $index['IdMarca'] ?></td>
        <td><?php echo $index['NombreMarca'] ?></td>        
        <td><?php echo $index['ImagenMarca'] ?></td>
        <td>[<a href="/admin/marca/edit-marca/idmarca/<?php echo $index['IdMarca'] ?>">Editar</a>]</td>
        <td>[<a href="/admin/marca/delete-marca/idmarca/<?php echo $index['IdMarca'] ?>">Eliminar</a>]</td>       
    </tr>

<?php } ?>
</table>