<div class="productos_colum_izq" >
    <?php
    $pagerData = array(
        'getPathInfo' => $this->getPathInfo,
        'params' => $this->params,
        'listaCategoriasNavigator' => $this->listaCategoriasNavigator
    );
    echo $this->partial('/partial/menucategorias.phtml', $pagerData)
    ?>
</div>
<div class="productos_colum_derc" >
    <div class="block_content">
        <?php
        echo $paginator = $this->paginationControl($this->productos, 'Sliding', '/paginator/Product.phtml');
        $params = array('productos' => $this->productos, 'paginator' => $paginator);
        echo $this->partial('/partial/listaProductosPaginator.phtml', $params)
        ?>
    </div>               
</div>

