insert into `producto` (`IdProducto`, `NombreProducto`, `IdArea`, `IdCategoriaProducto`, `IdSubCategoriaProducto`, `PrecioProducto`, `DescricionCortaProducto`, `SlugProducto`, `IdMarca`) values('','ProLiant MicroServer N40L','1','1','2',NULL,'HP ProLiant MicroServer N40L, 1P, 2 GB-U, Emb, SAT',NULL,'1');
insert into `producto` (`IdProducto`, `NombreProducto`, `IdArea`, `IdCategoriaProducto`, `IdSubCategoriaProducto`, `PrecioProducto`, `DescricionCortaProducto`, `SlugProducto`, `IdMarca`) values('','ProLiant ML330 G6','1','1','2',NULL,'Servidor HP ProLiant ML330 G6 E5603 1P, 2GB-U B110',NULL,'1');
insert into `producto` (`IdProducto`, `NombreProducto`, `IdArea`, `IdCategoriaProducto`, `IdSubCategoriaProducto`, `PrecioProducto`, `DescricionCortaProducto`, `SlugProducto`, `IdMarca`) values('','ProLiant ML350e Gen8','1','1','2',NULL,'Servidor básico HP ProLiant ML350e Gen 8 E5-2407 1',NULL,'1');
insert into `producto` (`IdProducto`, `NombreProducto`, `IdArea`, `IdCategoriaProducto`, `IdSubCategoriaProducto`, `PrecioProducto`, `DescricionCortaProducto`, `SlugProducto`, `IdMarca`) values('','ProLiant ML350p Gen8','1','1','2',NULL,'HP ProLiant ML350p Gen8 E5-2620 1P 4GB-R 460W PS S',NULL,'1');
insert into `producto` (`IdProducto`, `NombreProducto`, `IdArea`, `IdCategoriaProducto`, `IdSubCategoriaProducto`, `PrecioProducto`, `DescricionCortaProducto`, `SlugProducto`, `IdMarca`) values('','ProLiant ML350 G6','1','1','2',NULL,'Servidor / TV SAS HP ProLiant ML350 G6 E5606 1P 4',NULL,'1');
insert into `producto` (`IdProducto`, `NombreProducto`, `IdArea`, `IdCategoriaProducto`, `IdSubCategoriaProducto`, `PrecioProducto`, `DescricionCortaProducto`, `SlugProducto`, `IdMarca`) values('','','','','',NULL,'',NULL,'1');
insert into `producto` (`IdProducto`, `NombreProducto`, `IdArea`, `IdCategoriaProducto`, `IdSubCategoriaProducto`, `PrecioProducto`, `DescricionCortaProducto`, `SlugProducto`, `IdMarca`) values('','System x3300 M4','1','1','2',NULL,'El sistema IBM System x3300 M4 ofrece un equilibri',NULL,'2');
insert into `producto` (`IdProducto`, `NombreProducto`, `IdArea`, `IdCategoriaProducto`, `IdSubCategoriaProducto`, `PrecioProducto`, `DescricionCortaProducto`, `SlugProducto`, `IdMarca`) values('','System x3500 M4','1','1','2',NULL,'Este servidor de torre de dos procesadores y de al',NULL,'2');
insert into `producto` (`IdProducto`, `NombreProducto`, `IdArea`, `IdCategoriaProducto`, `IdSubCategoriaProducto`, `PrecioProducto`, `DescricionCortaProducto`, `SlugProducto`, `IdMarca`) values('','ProLiant serie ML150 G6','1','1','2',NULL,'Servidor HP ProLiant ML150 G6 E5502 1P, 1GB-U, 2x2',NULL,'1');
insert into `producto` (`IdProducto`, `NombreProducto`, `IdArea`, `IdCategoriaProducto`, `IdSubCategoriaProducto`, `PrecioProducto`, `DescricionCortaProducto`, `SlugProducto`, `IdMarca`) values('','System x3100 M4','1','1','2',NULL,'El x3100 M4 es una torre con una excelente relació',NULL,'2');
insert into `producto` (`IdProducto`, `NombreProducto`, `IdArea`, `IdCategoriaProducto`, `IdSubCategoriaProducto`, `PrecioProducto`, `DescricionCortaProducto`, `SlugProducto`, `IdMarca`) values('','System x3200 M3','1','1','2',NULL,'IBM System x3200 M3 ofrece mejores dispositivos y',NULL,'2');
insert into `producto` (`IdProducto`, `NombreProducto`, `IdArea`, `IdCategoriaProducto`, `IdSubCategoriaProducto`, `PrecioProducto`, `DescricionCortaProducto`, `SlugProducto`, `IdMarca`) values('','System x3400 M3','1','1','2',NULL,'El x3400 M3 ofrece flexibilidad, fiabilidad y segu',NULL,'2');
insert into `producto` (`IdProducto`, `NombreProducto`, `IdArea`, `IdCategoriaProducto`, `IdSubCategoriaProducto`, `PrecioProducto`, `DescricionCortaProducto`, `SlugProducto`, `IdMarca`) values('','System x3500 M3','1','1','2',NULL,'El sistema x3500 M3 proporciona una excelente esca',NULL,'2');
insert into `producto` (`IdProducto`, `NombreProducto`, `IdArea`, `IdCategoriaProducto`, `IdSubCategoriaProducto`, `PrecioProducto`, `DescricionCortaProducto`, `SlugProducto`, `IdMarca`) values('','System x3650 M4','1','1','1',NULL,NULL,NULL,'2');

